Ft/remove forms
tcp19/tcp-grand-resume pull request #33
Opened 2021-10-20 15:58 UTC by Mohamilr

You can delete entries now 

![image](https://user-images.githubusercontent.com/45388249/138128544-3e597fa1-42e7-4d0c-8721-e5bd0bdecb44.png)

![image](https://user-images.githubusercontent.com/45388249/138128583-21b61e42-bfbd-473a-82fc-c39660e142b1.png)

2021-10-20 17:19 UTC, adebayoileri commented
Good, this works functionally well

2021-10-20 17:22 UTC, adebayoileri commented
I'm thinking we could change the behaviour of the delete button appearing on all first sections i.e we should have at least one form section of the different parts of the CV  to be visible. 

 an additional check like this could do.


```
 setRecord({
                ...record,
                education: record.education.length > 1 && record.education.filter(  // d
                    (education, idx) => idx !== id
                ),
            });

```

2021-10-20 17:24 UTC, adebayoileri requested changes

2021-10-20 17:24 UTC, adebayoileri commented on pages/sections/CVForm.js
> +                                <Stack
or better still the delete button doesn't show when `index === 0`

2021-10-20 18:16 UTC, Mohamilr commented on pages/sections/CVForm.js
> +                                <Stack
alright, would update and revert

2021-10-21 01:46 UTC, Mohamilr commented
Changes made

What do you think about the layout on the languages when the button is added

![image](https://user-images.githubusercontent.com/45388249/138196997-be12347c-ce6d-4b3a-9258-2a5353d316c4.png)

2021-10-21 09:27 UTC, adebayoileri commented
> Changes made
> 
> What do you think about the layout on the languages when the button is added
> 
> ![image](https://user-images.githubusercontent.com/45388249/138196997-be12347c-ce6d-4b3a-9258-2a5353d316c4.png)

Looks a bit odd, but since the language can be an optional field I guess we can add the delete button to the first item

2021-10-21 10:02 UTC, Mohamilr commented
> > Changes made
> > What do you think about the layout on the languages when the button is added
> > ![image](https://user-images.githubusercontent.com/45388249/138196997-be12347c-ce6d-4b3a-9258-2a5353d316c4.png)
> 
> Looks a bit odd, but since the language can be an optional field I guess we can add the delete button to the first item

Does it mean the language section will no longer appear when the inputs are deleted or will it still remain.

2021-10-21 10:09 UTC, adebayoileri commented
> > > Changes made
> > > What do you think about the layout on the languages when the button is added
> > > ![image](https://user-images.githubusercontent.com/45388249/138196997-be12347c-ce6d-4b3a-9258-2a5353d316c4.png)
> > 
> > 
> > Looks a bit odd, but since the language can be an optional field I guess we can add the delete button to the first item
> 
> Does it mean the language section will no longer appear when the inputs are deleted or will it still remain.

It can still appear would just show a placeholder e.g "No Available Languages"

2021-10-21 15:45 UTC, Mohamilr commented
Done @adebayoileri 
![image](https://user-images.githubusercontent.com/45388249/138312192-06a6b5b3-7789-47f4-bfc3-4a58dadc1266.png)

2021-10-21 18:58 UTC, adebayoileri approved these changes

2021-10-21 18:58 UTC, merged